Updated ovpn_run to only supply the client config when starting ovpn

diff --git a/bin/ovpn_run b/bin/ovpn_run
--- a/bin/ovpn_run
+++ b/bin/ovpn_run
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-# Run the OpenVPN server normally
+# Run the OpenVPN Client Normally
 #
 
 if [ "$DEBUG" == "1" ]; then
@@ -50,51 +50,48 @@ function setupIptablesAndRouting {
 }
 
 
-addArg "--config" "$OPENVPN/openvpn.conf"
+addArg "--config" "$OPENVPN/client.ovpn"
+#addArg "--config" "$OPENVPN/openvpn.conf"
 
 source "$OPENVPN/ovpn_env.sh"
 
-mkdir -p /dev/net
-if [ ! -c /dev/net/tun ]; then
-    mknod /dev/net/tun c 10 200
-fi
-
-if [ -d "$OPENVPN/ccd" ]; then
-    addArg "--client-config-dir" "$OPENVPN/ccd"
-fi
+#mkdir -p /dev/net
+#if [ ! -c /dev/net/tun ]; then
+#    mknod /dev/net/tun c 10 200
+#fi
 
 # When using --net=host, use this to specify nat device.
-[ -z "$OVPN_NATDEVICE" ] && OVPN_NATDEVICE=eth0
+#[ -z "$OVPN_NATDEVICE" ] && OVPN_NATDEVICE=eth0
 
 # Setup NAT forwarding if requested
-if [ "$OVPN_DEFROUTE" != "0" ] || [ "$OVPN_NAT" == "1" ] ; then
+#if [ "$OVPN_DEFROUTE" != "0" ] || [ "$OVPN_NAT" == "1" ] ; then
 	# call function to setup iptables rules and routing
 	# this allows rules to be customized by supplying
 	# a replacement function in, for example, ovpn_env.sh
-	setupIptablesAndRouting
-fi
+#	setupIptablesAndRouting
+#fi
 
 # Use a copy of crl.pem as the CRL Needs to be readable by the user/group
 # OpenVPN is running as.  Only pass arguments to OpenVPN if it's found.
-if [ "$EASYRSA_PKI/crl.pem" -nt "$OPENVPN/crl.pem" ]; then
-    cp -f "$EASYRSA_PKI/crl.pem" "$OPENVPN/crl.pem"
-    chmod 644 "$OPENVPN/crl.pem"
-fi
+#if [ "$EASYRSA_PKI/crl.pem" -nt "$OPENVPN/crl.pem" ]; then
+#    cp -f "$EASYRSA_PKI/crl.pem" "$OPENVPN/crl.pem"
+#    chmod 644 "$OPENVPN/crl.pem"
+#fi
 
-if [ -r "$OPENVPN/crl.pem" ]; then
-    addArg "--crl-verify" "$OPENVPN/crl.pem"
-fi
+#if [ -r "$OPENVPN/crl.pem" ]; then
+#    addArg "--crl-verify" "$OPENVPN/crl.pem"
+#fi
 
-ip -6 route show default 2>/dev/null
-if [ $? = 0 ]; then
-    echo "Enabling IPv6 Forwarding"
+#ip -6 route show default 2>/dev/null
+#if [ $? = 0 ]; then
+#    echo "Enabling IPv6 Forwarding"
     # If this fails, ensure the docker container is run with --privileged
     # Could be side stepped with `ip netns` madness to drop privileged flag
 
-    sysctl -w net.ipv6.conf.all.disable_ipv6=0 || echo "Failed to enable IPv6 support"
-    sysctl -w net.ipv6.conf.default.forwarding=1 || echo "Failed to enable IPv6 Forwarding default"
-    sysctl -w net.ipv6.conf.all.forwarding=1 || echo "Failed to enable IPv6 Forwarding"
-fi
+#    sysctl -w net.ipv6.conf.all.disable_ipv6=0 || echo "Failed to enable IPv6 support"
+#    sysctl -w net.ipv6.conf.default.forwarding=1 || echo "Failed to enable IPv6 Forwarding default"
+#    sysctl -w net.ipv6.conf.all.forwarding=1 || echo "Failed to enable IPv6 Forwarding"
+#fi
 
 echo "Running 'openvpn ${ARGS[@]} ${USER_ARGS[@]}'"
 exec openvpn ${ARGS[@]} ${USER_ARGS[@]}
